config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  root 'auth#login'

  resources :feeds do
    get 'page/:page', action: :show, on: :member
    collection do
      match 'discover', via: :post
      match 'update_feed_group', via: :post
    end

    resources :feed_items, only: [:show], as: :items do
      member do
        get 'mark/read' => 'feed_items#mark_read'
        get 'mark/unread' => 'feed_items#mark_unread'
        get 'mark/saved' => 'feed_items#mark_saved'
        get 'mark/unsaved' => 'feed_items#mark_unsaved'
      end
    end
  end
  resources :groups, except: [:new]

  match 'setup' => 'setup#setup', via: [:get, :post], as: :setup

  match 'login' => 'auth#login', via: [:get, :post], as: :login
  delete 'login' => 'auth#logout', as: :logout


  # Fever API Endpoint
  get   '/fever' => 'fever#fever'
  post  '/fever' => 'fever#fever'
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :feeds
  has_many :feed_items, through: :feeds

  before_destroy :add_feeds_to_default_group

  def add_feed(feed)
    feeds << feed
  end

  def remove_feed(feed)
    feeds.delete(feed)
  end

  def add_feeds_to_default_group
    default_group = User.find(user_id).groups.find_by(default: true)

    feeds.each do |feed|
      default_group.add_feed(feed)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_logged_in!

  def index
    @groups = current_user.groups
    @group = Group.new
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update_attributes(group_params)
      redirect_to groups_path
    end
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to groups_path
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    if !@group.default? && @group.destroy
      redirect_to groups_path
    end
  end

  private

    def group_params
      params.require(:group).permit(:title)
    end

end

app/views/groups/_form.html.slim
= simple_form_for @group do |f|
  = f.input :title
  = f.button :submit

app/views/groups/_group.html.slim
.group
  = link_to 'edit', edit_group_path(group.id), id: "edit-group-#{group.id}", class: 'button'
  h1 = group.title
  p #{group.feeds.count} Feeds

app/views/groups/edit.html.slim
.form-wrap
  h3 Edit Group
  = render 'form'

  p = link_to 'Delete this Group', group_path(@group.id), method: :delete if !@group.default?

app/views/groups/index.html.slim
.form-wrap
  h3 Add a new Group
  = render 'form'

.groups
  ul
    - @groups.each do |group|
      li = render group