config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  root 'auth#login'

  resources :feeds do
    get 'page/:page', action: :show, on: :member
    collection do
      match 'discover', via: :post
      match 'update_feed_group', via: :post
    end

    resources :feed_items, only: [:show], as: :items do
      member do
        get 'mark/read' => 'feed_items#mark_read'
        get 'mark/unread' => 'feed_items#mark_unread'
        get 'mark/saved' => 'feed_items#mark_saved'
        get 'mark/unsaved' => 'feed_items#mark_unsaved'
      end
    end
  end
  resources :groups, except: [:new]

  match 'setup' => 'setup#setup', via: [:get, :post], as: :setup

  match 'login' => 'auth#login', via: [:get, :post], as: :login
  delete 'login' => 'auth#logout', as: :logout


  # Fever API Endpoint
  get   '/fever' => 'fever#fever'
  post  '/fever' => 'fever#fever'
end

app/models/feed_item.rb
class FeedItem < ActiveRecord::Base
  include FeedItemHelper

  belongs_to :feed
  has_many :feed_item_reads
  has_many :feed_item_stars

  validates :feed_id, :title, :url, presence: true

  scope :clean, -> { where cleaned: true }

  def mark_as(mark, user_id)
    case mark
      when 'read'
        unless feed_item_reads.find_by(feed_item_id: id, user_id: user_id)
          feed_item_reads.create(feed_id: feed_id, user_id: user_id)
        end
      when 'unread'
        feed_item_reads.find_by(feed_item_id: id, user_id: user_id).try(:destroy)
      when 'saved'
        unless feed_item_stars.find_by(feed_item_id: id, user_id: user_id)
          feed_item_stars.create(feed_id: feed_id, user_id: user_id)
        end
      when 'unsaved'
        feed_item_stars.find_by(feed_item_id: id, user_id: user_id).try(:destroy)
    end
  end

  def next_item
    FeedItem.clean.where('id > ? AND feed_id = ?', self.id, self.feed_id).limit(1).first
  end

  def previous_item
    FeedItem.clean.where('id < ? AND feed_id = ?', self.id, self.feed_id).last
  end

  def word_count
    html.split(' ').count
  end

  def length_in_time(wpm = 130)
    word_count.to_f / wpm.to_f
  end

end

app/controllers/feed_items_controller.rb
class FeedItemsController < ApplicationController
  before_action :ensure_logged_in!
  before_action :set_feed_item, only: [:show, :mark_read, :mark_unread, :mark_saved, :mark_unsaved]

  def show
    @feed_item.mark_as('read', current_user.id)
    @next_item = @feed_item.next_item
    @previous_item = @feed_item.previous_item
  end

  def mark_read
    @feed_item.mark_as('read', current_user.id)

    respond_to do |format|
      format.js
    end
  end

  def mark_unread
    @feed_item.mark_as('unread', current_user.id)

    respond_to do |format|
      format.js
    end
  end

  def mark_saved
    @feed_item.mark_as('saved', current_user.id)

    respond_to do |format|
      format.js
    end
  end

  def mark_unsaved
    @feed_item.mark_as('unsaved', current_user.id)

    respond_to do |format|
      format.js
    end
  end

  private

    def set_feed_item
      @feed_item = current_user.feeds.find(params[:feed_id]).feed_items.find(params[:id])
    end

end

app/helpers/feed_item_helper.rb
module FeedItemHelper
end

app/views/feed_items/mark_read.js.erb
console.log("mark_read");
$('.mark_unread').text('Marked as unread!')

app/views/feed_items/mark_saved.js.erb
$('.mark_as_link').html('<%= link_to(t('feed_item.is_saved').html_safe, mark_unsaved_feed_item_path, remote: true, class: 'button toggle_save_unsave mark_unsaved') %>');

app/views/feed_items/mark_unread.js.erb
console.log("mark_unread");
$('.mark_unread').text('Marked as unread!')

app/views/feed_items/mark_unsaved.js.erb
$('.mark_as_link').html('<%= link_to(t('feed_item.is_unsaved').html_safe, mark_saved_feed_item_path, remote: true, class: 'button toggle_save_unsave mark_saved') %>');

app/views/feed_items/show.html.slim
= div_for @feed_item

  .options_header
    .breadcrumb
      ul
        li = link_to 'Feeds', feeds_path
        li = link_to @feed_item.feed.title, feed_path(@feed_item.feed)
        li = truncate @feed_item.title, length: 30

    .pagination
      = link_to t('previous'), feed_item_path(@feed_item.feed_id, @previous_item), class: 'button previous-page' if @previous_item
      = link_to t('next'), feed_item_path(@feed_item.feed_id, @next_item), class: 'button next-page' if @next_item


  .scroll_content
    .full_content
      .header
        ul
          - if current_user.item_read?(@feed_item.id)
            li = link_to 'Mark unread', mark_unread_feed_item_path, remote: true, class: 'button mark_unread'

          - if current_user.item_starred?(@feed_item.id)
            li.mark_as_link = link_to t('feed_item.is_saved').html_safe, mark_unsaved_feed_item_path,
              remote: true, class: 'button toggle_save_unsave mark_unsaved'
          - else
            li.mark_as_link = link_to t('feed_item.is_unsaved').html_safe, mark_saved_feed_item_path,
              remote: true, class: 'button toggle_save_unsave mark_saved'
          li = link_to(t('feed_item.url_open').html_safe, @feed_item.url, target: 'blank', class: 'button url_open')

        .created_on_time  = l @feed_item.created_on_time
        .word_count       = @feed_item.html.split(' ').count.to_s + t('feed_item.word_count')
        .length_in_time   = time_ago_in_words(@feed_item.length_in_time.minutes.from_now)

      .feed_content
        h1.feed_item_title = HTMLEntities.new.decode @feed_item.title
        = @feed_item.html.html_safe