config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  root 'auth#login'

  resources :feeds do
    get 'page/:page', action: :show, on: :member
    collection do
      match 'discover', via: :post
      match 'update_feed_group', via: :post
    end

    resources :feed_items, only: [:show], as: :items do
      member do
        get 'mark/read' => 'feed_items#mark_read'
        get 'mark/unread' => 'feed_items#mark_unread'
        get 'mark/saved' => 'feed_items#mark_saved'
        get 'mark/unsaved' => 'feed_items#mark_unsaved'
      end
    end
  end
  resources :groups, except: [:new]

  match 'setup' => 'setup#setup', via: [:get, :post], as: :setup

  match 'login' => 'auth#login', via: [:get, :post], as: :login
  delete 'login' => 'auth#logout', as: :logout


  # Fever API Endpoint
  get   '/fever' => 'fever#fever'
  post  '/fever' => 'fever#fever'
end

app/views/layouts/_head.html.slim
head
  title HappyFeed
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  meta name="viewport" content="width=device-width, initial-scale=1.0"
  meta name="apple-mobile-web-app-capable" content="yes"
  meta name="apple-mobile-web-app-status-bar-style" content="black"

app/views/layouts/application.html.slim
doctype html
html
  = render 'layouts/head'

  body
    .all-wrap
      .sidebar
        .header
          .logo = image_tag 'logo.png'

        - if logged_in?
          .navigation
            ul
              li = link_to t('.sidebar.add_feed').html_safe, new_feed_path, rel: 'modal:open'
              li = link_to t('.sidebar.manage_groups').html_safe, groups_path

          = render 'layouts/sidebar/group_navigation'

          .secondary-navigation
            .auth = current_user.email
            .logout = link_to 'logout', logout_path, method: :delete, class: 'button'


      .content-wrap
        - if notice
          .notice = notice
        - if alert
          .alert = alert

        = yield